"use client";
import { Provider, defaultTheme, SSRProvider } from "@adobe/react-spectrum";
import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SSRProvider>
          <Provider theme={defaultTheme}>{children}</Provider>
        </SSRProvider>
      </body>
    </html>
  );
}
